export enum AdvantageType{
  TEDFREE = "TEDFREE",
  CARDFREE = "CARDFREE",
  CASHBACK1 = "CASHBACK1",
  CASHBACK2 = "CASHBACK2",
  CASHBACK5 = "CASHBACK5",
  CASHBACK10 = "CASHBACK10",
  CDB150 = "CDB150",
  CONSULTANCY = "CONSULTANCY",
  CARDPLATINUM = "CARDPLATINUM",
  CARDBLACK = "CARDBLACK",
  MILESILIMITED = "MILESILIMITED",
  FEE1 = "FEE1",
  FEE2 = "FEE2",
  APPROVAL24 = "APPROVAL24",
  FEELESSTOPAY = "FEELESSTOPAY"
}