export enum NotificationType{
  LOGIN = 'LOGIN',
  ACCOUNT_CREATED = "ACCOUNT_CREATED",
  KEY_CREATED = "KEY_CREATED",
  KEY_DELETED = "KEY_DELETED",
  KEY_EDITED = "KEY_EDITED",
  TRANSFER_MADE = "TRANSFER_MADE",
  TRANSFER_RECEIVE = "TRANSFER_RECEIVE" ,
  TRANSFER_SCHEDULED = "TRANSFER_SCHEDULED",
  INVESTMENT = "INVESTMENT",
  DEPOSIT = "DEPOSIT",
  BILLET_GENERATED = "BILLET_GENERATED",
  BILLET_WILL_EXPIRE = "BILLET_WILL_EXPIRE",
  BILLET_DUE = "BILLET_DUE",
  ACCOUNT_EDITED = "ACCOUNT_EDITED",
  CREDITCARD_REQUESTED = "CREDITCARD_REQUESTED",
  CREDITCARD_RESPONSED = "CREDITCARD_RESPONSED",
  CREDITCARD_FAILED = "CREDITCARD_FAILED"
}